import Head from 'next/head'
import styles from '../styles/Layout.module.scss'
import Nav from './Nav';

const Layout = ({children}: any) => {

  return (
    <>
      <Head>
        <title>To Do List</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
      <div className='styles.container'>
        <main className={styles.main}>
        {/* <h1>Hola!</h1> */}
        {children}
        </main>
      </div>
    </>
  )
}
export default Layout;